<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<RuntimeHostConfigurationOption Include="System.Runtime.Loader.UseRidGraph" Value="true" />
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="MediaInfo.Wrapper.Core" Version="26.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\IPlugins\IPlugins.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MediaInfo.Wrapper.Core">
      <HintPath>..\..\..\..\MP-MediaInfo-master\MediaInfo.Wrapper\bin\Debug\net8.0\MediaInfo.Wrapper.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
